#! /usr/bin/python3

# Munin weather plugin
# 
# A Munin plugin that retrieves the current weather from Apple WeatherKit
# 
# If you have a developer account, you can use Apple WeatherKit
#
# The developer account includes 500 K calls per month.
# This restriction allows 56 locations, calculated as 500 K requests/month / 8928 req/month/location
#


import datetime
import os
import sys

import weather
import weatherkit


verbose = True if os.getenv('MUNIN_DEBUG') == '1' else False

def verboselog(s):
    if verbose:
        sys.stderr.write('{}: {}\n'.format(plugin_name, s))


_locations = {
    'Christchurch.nz.place'  : ( 'Christchurch, NZ'       , -43.4821,  172.5500,   37),
    'Lyttelton.nz.place'     : ( 'Lyttelton, NZ'          , -43.6000,  172.7200,    0),
    'Nelson.nz.place'        : ( 'Nelson, NZ'             , -41.2980,  173.2210,    5),
    'Scott-Base.nz.place'    : ( 'Scott Base, NZ'         , -77.8491,  166.7682,   10),

    'SANAE4.za.place'        : ( 'SANAE IV, ZA'           , -71.6724,   -2.8249,  850),

    'Wichita.ka.us.place'    : ( 'Wichita, KA, US'        ,  37.6889,  -97.3361,  400),
    'Amundsen-Scott.us.place': ( 'Amundsen-Scott Base, US', -90.0000,    0.0000, 2835),
}


_graph_specs = [
    {   
        'name': 'temperature',
        'config': [
            'graph_title Temperature',
            'graph_category weather',
            'graph_args --lower-limit -10 --upper-limit 40',
            'graph_vlabel °C',
        ],
        'fields': [
            {
                'name': 'air_temperature',
                'config': [
                    'label Air temperature (°C)',
                ],
                'fmt': '{:0.1f}',
                'param': 'temperature_C',
            },
        ],
    },

    {   
        'name': 'humidity',
        'config': [
            'graph_title Humidity',
            'graph_category weather',
            'graph_args --lower-limit 0 --upper-limit 100 --rigid',
            'graph_vlabel Humidity (%RH)',
        ],
        'fields': [
            {
                'name': 'air_humidity',
                'config': [
                    'label Air humidity (%RH)',
                ],
                'fmt': '{:0.0f}',
                'param': 'relative_humidity_pc',
            },
        ],
    },

    {
        'name': 'pressure',
        'config': [
            'graph_title Pressure',
            'graph_category weather',
            'graph_args --lower-limit 900 --upper-limit 1100 --rigid --y-grid 10:5',
            'graph_scale no',
            'graph_vlabel hPa',
        ],
        'fields': [
            {
                'name': 'air_pressure',
                'config': [
                    'label Air pressure (hPa)',
                 ],
                 'fmt': '{:0.0f}',
                 'param': 'pressure_hPa',
             },
         ],
    },
    
    {
        'name': 'windspeed',
        'config': [
            'graph_title Wind speed',
            'graph_category weather',
            'graph_args --lower-limit 0 --upper-limit 40 --rigid',
            'graph_scale no',
            'graph_vlabel knots',
        ],
        'fields': [
            {
                'name': 'windspeed',
                'config': [
                    'label Wind speed (knots)',
                    'cdef windspeed,1.944,*',
                ],
                'fmt': '{:0.1f}',
                'param': 'wind_speed_m_s',
            },
            {
                'name': 'windgust',
                'config': [
                    'label Wind gust (knots)',
                    'cdef windgust,1.944,*',
                ],
                'fmt': '{:0.1f}',
                'param': 'wind_gust_m_s',
            },
        ],
    },

    {
        'name': 'winddirection',
        'config': [
            'graph_title Wind direction',
            'graph_category weather',
            'graph_args --lower-limit 0 --upper-limit 360 --rigid --y-grid 30:3',
            'graph_scale no',
            'graph_vlabel Wind direction (°)',
            'graph_order winddirection1',
        ],
        'fields': [
            {
                'name': 'windvector_E',
                'config': [
                    'label Wind vector E',
                    'graph no',
                ],
                'fmt': '{:0.3f}',
                'param': 'wind_vector_E',
            },
            {
                'name': 'windvector_N',
                'config': [
                    'label Wind vector N',
                    'graph no',
                ],
                'fmt': '{:0.3f}',
                'param': 'wind_vector_N',
            },
            {
                'name': 'winddirection1',
                'config': [
                    'label Wind direction (°)',
                    'cdef windvector_N,windvector_E,ATAN2,RAD2DEG,90,EXC,-,360,+,360,%',
                ],
                'fmt': None,
                'param': None,
            },
        ],
    },

    {
        'name': 'winddirection_deg',
        'config': [
            'graph_title Wind direction deg',
            'graph_category weather',
            'graph_args --lower-limit 0 --upper-limit 360 --rigid --y-grid 30:3',
            'graph_scale no',
            'graph_vlabel Wind direction (°)',
        ],
        'fields': [
            {
                'name': 'wind_direction_deg',
                'config': [
                    'label Wind direction deg',
                ],
                'fmt': '{:0.0f}',
                'param': 'wind_direction_deg',
            },
        ],
    },
    
]


def config(hostname, location):
    print("host_name {}".format(hostname))
    print()

    for gr in _graph_specs:
        gr_name = gr['name']
        print('multigraph {}_{}'.format(script_name, gr_name))
        
        for cfg in gr['config']:
            print(cfg)
        
        for fld in gr['fields']:
            fld_name = fld['name']
            for cfg in fld['config']:
                print('{}.{}'.format(fld_name, cfg))
        print()
        
        
def fetch(hostname, loc):
    location = { k: loc[i] for i, k in enumerate(['name', 'lat', 'lon', 'alt']) }
    secrets = {
        'auth_token': os.environ['AWK_AUTH_TOKEN']
    }
   
    report = weather.load_report(weatherkit.service, location, secrets)

    for gr in _graph_specs:
        gr_name = gr['name']
        print('multigraph {}_{}'.format(script_name, gr_name))
        
        for fld in gr['fields']:
            fld_name = fld['name']
            param_name = fld['param']
            fmt = fld['fmt']
            
            if param_name is not None:
                try:
                    value = report._asdict()[param_name]
                except KeyError:
                    value = None
                    
                if value is not None:                    
                    value_fmt = fmt.format(value)
                else:
                    value_fmt = 'U'
                    
                print('{}.value {}'.format(fld_name, value_fmt))
        print()
    

plugin_name = os.path.basename(sys.argv[0])
script_name, hostname = plugin_name.split('_')
location = _locations[hostname]

if len(sys.argv) > 1:
    cmd = sys.argv[1]
    if cmd == 'config':
        config(hostname, location)
        if True:  # if we support dirtyconfig
            fetch(hostname, location)
        sys.exit(0)

    if cmd == 'suggest':
        sys.exit(0)

    verboselog('unknown argument "{}"'.format(cmd))
    exit(1)

fetch(hostname, location)

